package com.jimi.smt.eps_server.entity;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.name
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.description
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.name
     *
     * @return the value of config.name
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.name
     *
     * @param name the value for config.name
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.description
     *
     * @return the value of config.description
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.description
     *
     * @param description the value for config.description
     *
     * @mbggenerated Tue Nov 14 13:20:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}