package com.jimi.smt.eps_server.entity;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.id
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.name
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.description
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.line
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.enabled
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.alias
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String alias;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.id
     *
     * @return the value of config.id
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.id
     *
     * @param id the value for config.id
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.name
     *
     * @return the value of config.name
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.name
     *
     * @param name the value for config.name
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.description
     *
     * @return the value of config.description
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.description
     *
     * @param description the value for config.description
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.line
     *
     * @return the value of config.line
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.line
     *
     * @param line the value for config.line
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.enabled
     *
     * @return the value of config.enabled
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.enabled
     *
     * @param enabled the value for config.enabled
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.alias
     *
     * @return the value of config.alias
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.alias
     *
     * @param alias the value for config.alias
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }
}