package com.jimi.smt.eps_server.entity;

import java.util.Date;

public class ProgramItemVisit extends ProgramItemVisitKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.scan_lineseat
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String scanLineseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.scan_material_no
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String scanMaterialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.last_operation_type
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Integer lastOperationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.store_issue_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean storeIssueResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.store_issue_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date storeIssueTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.feed_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean feedResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.feed_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date feedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.change_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean changeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.change_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_all_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean checkAllResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_all_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date checkAllTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.first_check_all_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Boolean firstCheckAllResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.first_check_all_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date firstCheckAllTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.last_operation_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private Date lastOperationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.scan_lineseat
     *
     * @return the value of program_item_visit.scan_lineseat
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getScanLineseat() {
        return scanLineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.scan_lineseat
     *
     * @param scanLineseat the value for program_item_visit.scan_lineseat
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setScanLineseat(String scanLineseat) {
        this.scanLineseat = scanLineseat == null ? null : scanLineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.scan_material_no
     *
     * @return the value of program_item_visit.scan_material_no
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getScanMaterialNo() {
        return scanMaterialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.scan_material_no
     *
     * @param scanMaterialNo the value for program_item_visit.scan_material_no
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setScanMaterialNo(String scanMaterialNo) {
        this.scanMaterialNo = scanMaterialNo == null ? null : scanMaterialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.last_operation_type
     *
     * @return the value of program_item_visit.last_operation_type
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Integer getLastOperationType() {
        return lastOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.last_operation_type
     *
     * @param lastOperationType the value for program_item_visit.last_operation_type
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setLastOperationType(Integer lastOperationType) {
        this.lastOperationType = lastOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.store_issue_result
     *
     * @return the value of program_item_visit.store_issue_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getStoreIssueResult() {
        return storeIssueResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.store_issue_result
     *
     * @param storeIssueResult the value for program_item_visit.store_issue_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setStoreIssueResult(Boolean storeIssueResult) {
        this.storeIssueResult = storeIssueResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.store_issue_time
     *
     * @return the value of program_item_visit.store_issue_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getStoreIssueTime() {
        return storeIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.store_issue_time
     *
     * @param storeIssueTime the value for program_item_visit.store_issue_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setStoreIssueTime(Date storeIssueTime) {
        this.storeIssueTime = storeIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.feed_result
     *
     * @return the value of program_item_visit.feed_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getFeedResult() {
        return feedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.feed_result
     *
     * @param feedResult the value for program_item_visit.feed_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setFeedResult(Boolean feedResult) {
        this.feedResult = feedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.feed_time
     *
     * @return the value of program_item_visit.feed_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getFeedTime() {
        return feedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.feed_time
     *
     * @param feedTime the value for program_item_visit.feed_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setFeedTime(Date feedTime) {
        this.feedTime = feedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.change_result
     *
     * @return the value of program_item_visit.change_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getChangeResult() {
        return changeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.change_result
     *
     * @param changeResult the value for program_item_visit.change_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setChangeResult(Boolean changeResult) {
        this.changeResult = changeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.change_time
     *
     * @return the value of program_item_visit.change_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.change_time
     *
     * @param changeTime the value for program_item_visit.change_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_result
     *
     * @return the value of program_item_visit.check_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_result
     *
     * @param checkResult the value for program_item_visit.check_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setCheckResult(Boolean checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_time
     *
     * @return the value of program_item_visit.check_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_time
     *
     * @param checkTime the value for program_item_visit.check_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_all_result
     *
     * @return the value of program_item_visit.check_all_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getCheckAllResult() {
        return checkAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_all_result
     *
     * @param checkAllResult the value for program_item_visit.check_all_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setCheckAllResult(Boolean checkAllResult) {
        this.checkAllResult = checkAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_all_time
     *
     * @return the value of program_item_visit.check_all_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getCheckAllTime() {
        return checkAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_all_time
     *
     * @param checkAllTime the value for program_item_visit.check_all_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setCheckAllTime(Date checkAllTime) {
        this.checkAllTime = checkAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.first_check_all_result
     *
     * @return the value of program_item_visit.first_check_all_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Boolean getFirstCheckAllResult() {
        return firstCheckAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.first_check_all_result
     *
     * @param firstCheckAllResult the value for program_item_visit.first_check_all_result
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setFirstCheckAllResult(Boolean firstCheckAllResult) {
        this.firstCheckAllResult = firstCheckAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.first_check_all_time
     *
     * @return the value of program_item_visit.first_check_all_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getFirstCheckAllTime() {
        return firstCheckAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.first_check_all_time
     *
     * @param firstCheckAllTime the value for program_item_visit.first_check_all_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setFirstCheckAllTime(Date firstCheckAllTime) {
        this.firstCheckAllTime = firstCheckAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.last_operation_time
     *
     * @return the value of program_item_visit.last_operation_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public Date getLastOperationTime() {
        return lastOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.last_operation_time
     *
     * @param lastOperationTime the value for program_item_visit.last_operation_time
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setLastOperationTime(Date lastOperationTime) {
        this.lastOperationTime = lastOperationTime;
    }
}