package com.jimi.smt.eps_server.entity;

public class ProgramItemKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item.program_id
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String programId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item.lineseat
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String lineseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item.material_no
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    private String materialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item.program_id
     *
     * @return the value of program_item.program_id
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item.program_id
     *
     * @param programId the value for program_item.program_id
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setProgramId(String programId) {
        this.programId = programId == null ? null : programId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item.lineseat
     *
     * @return the value of program_item.lineseat
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getLineseat() {
        return lineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item.lineseat
     *
     * @param lineseat the value for program_item.lineseat
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setLineseat(String lineseat) {
        this.lineseat = lineseat == null ? null : lineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item.material_no
     *
     * @return the value of program_item.material_no
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item.material_no
     *
     * @param materialNo the value for program_item.material_no
     *
     * @mbggenerated Tue Nov 21 17:14:15 CST 2017
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }
}