package com.jimi.smt.eps.serversocket.entity;

import java.util.Date;

public class BoardNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board_num.id
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board_num.num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board_num.time
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board_num.line
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private String line;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board_num.id
     *
     * @return the value of board_num.id
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board_num.id
     *
     * @param id the value for board_num.id
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board_num.num
     *
     * @return the value of board_num.num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board_num.num
     *
     * @param num the value for board_num.num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board_num.time
     *
     * @return the value of board_num.time
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board_num.time
     *
     * @param time the value for board_num.time
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board_num.line
     *
     * @return the value of board_num.line
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board_num.line
     *
     * @param line the value for board_num.line
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }
}