package com.jimi.smt.esp_server.mapper;

import com.jimi.smt.esp_server.entity.ProgramBackup;
import com.jimi.smt.esp_server.entity.ProgramBackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgramBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int countByExample(ProgramBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int deleteByExample(ProgramBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int insert(ProgramBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int insertSelective(ProgramBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    List<ProgramBackup> selectByExample(ProgramBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    ProgramBackup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProgramBackup record, @Param("example") ProgramBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int updateByExample(@Param("record") ProgramBackup record, @Param("example") ProgramBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int updateByPrimaryKeySelective(ProgramBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_backup
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    int updateByPrimaryKey(ProgramBackup record);
}