package com.jimi.smt.esp_server.mapper;

import com.jimi.smt.esp_server.entity.ProgramItemBackup;
import com.jimi.smt.esp_server.entity.ProgramItemBackupExample;
import com.jimi.smt.esp_server.entity.ProgramItemBackupKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgramItemBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int countByExample(ProgramItemBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int deleteByExample(ProgramItemBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int deleteByPrimaryKey(ProgramItemBackupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int insert(ProgramItemBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int insertSelective(ProgramItemBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    List<ProgramItemBackup> selectByExample(ProgramItemBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    ProgramItemBackup selectByPrimaryKey(ProgramItemBackupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProgramItemBackup record, @Param("example") ProgramItemBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int updateByExample(@Param("record") ProgramItemBackup record, @Param("example") ProgramItemBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int updateByPrimaryKeySelective(ProgramItemBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_backup
     *
     * @mbggenerated Mon Oct 23 15:52:35 CST 2017
     */
    int updateByPrimaryKey(ProgramItemBackup record);
}