package com.jimi.smt.eps.serversocket.mapper;

import com.jimi.smt.eps.serversocket.entity.BoardNum;
import com.jimi.smt.eps.serversocket.entity.BoardNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int countByExample(BoardNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int deleteByExample(BoardNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int insert(BoardNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int insertSelective(BoardNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    List<BoardNum> selectByExample(BoardNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    BoardNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") BoardNum record, @Param("example") BoardNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int updateByExample(@Param("record") BoardNum record, @Param("example") BoardNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int updateByPrimaryKeySelective(BoardNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_num
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    int updateByPrimaryKey(BoardNum record);
}