package com.jimi.smt.eps.alarmsocket.mapper;

import com.jimi.smt.eps.alarmsocket.entity.ProgramItemVisit;
import com.jimi.smt.eps.alarmsocket.entity.ProgramItemVisitExample;
import com.jimi.smt.eps.alarmsocket.entity.ProgramItemVisitKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgramItemVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int countByExample(ProgramItemVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int deleteByExample(ProgramItemVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int deleteByPrimaryKey(ProgramItemVisitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int insert(ProgramItemVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int insertSelective(ProgramItemVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    List<ProgramItemVisit> selectByExample(ProgramItemVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    ProgramItemVisit selectByPrimaryKey(ProgramItemVisitKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProgramItemVisit record, @Param("example") ProgramItemVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int updateByExample(@Param("record") ProgramItemVisit record, @Param("example") ProgramItemVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int updateByPrimaryKeySelective(ProgramItemVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_item_visit
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    int updateByPrimaryKey(ProgramItemVisit record);
}