package com.jimi.smt.eps.display.entity;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.protocol
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.serial_no
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private Short serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.data
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.sender_ip
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private String senderIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.receiver_ip
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private String receiverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.time
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.protocol
     *
     * @return the value of log.protocol
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.protocol
     *
     * @param protocol the value for log.protocol
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.serial_no
     *
     * @return the value of log.serial_no
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public Short getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.serial_no
     *
     * @param serialNo the value for log.serial_no
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setSerialNo(Short serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.data
     *
     * @return the value of log.data
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.data
     *
     * @param data the value for log.data
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.sender_ip
     *
     * @return the value of log.sender_ip
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public String getSenderIp() {
        return senderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.sender_ip
     *
     * @param senderIp the value for log.sender_ip
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setSenderIp(String senderIp) {
        this.senderIp = senderIp == null ? null : senderIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.receiver_ip
     *
     * @return the value of log.receiver_ip
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public String getReceiverIp() {
        return receiverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.receiver_ip
     *
     * @param receiverIp the value for log.receiver_ip
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setReceiverIp(String receiverIp) {
        this.receiverIp = receiverIp == null ? null : receiverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.time
     *
     * @return the value of log.time
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.time
     *
     * @param time the value for log.time
     *
     * @mbggenerated Thu Mar 01 14:19:24 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}