package com.jimi.smt.eps.printer.mapper;

import com.jimi.smt.eps.printer.entity.StockLog;
import com.jimi.smt.eps.printer.entity.StockLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int countByExample(StockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int deleteByExample(StockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int insert(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int insertSelective(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    List<StockLog> selectByExample(StockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    StockLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") StockLog record, @Param("example") StockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int updateByExample(@Param("record") StockLog record, @Param("example") StockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int updateByPrimaryKeySelective(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    int updateByPrimaryKey(StockLog record);
}