package com.jimi.smt.esp_server.entity;

import java.util.Date;

public class Operation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.id
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operator
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.time
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.type
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.result
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.lineseat
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private String lineseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.material_no
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private String materialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.old_material_no
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    private String oldMaterialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.id
     *
     * @return the value of operation.id
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.id
     *
     * @param id the value for operation.id
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operator
     *
     * @return the value of operation.operator
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operator
     *
     * @param operator the value for operation.operator
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.time
     *
     * @return the value of operation.time
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.time
     *
     * @param time the value for operation.time
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.type
     *
     * @return the value of operation.type
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.type
     *
     * @param type the value for operation.type
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.result
     *
     * @return the value of operation.result
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.result
     *
     * @param result the value for operation.result
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.lineseat
     *
     * @return the value of operation.lineseat
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public String getLineseat() {
        return lineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.lineseat
     *
     * @param lineseat the value for operation.lineseat
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setLineseat(String lineseat) {
        this.lineseat = lineseat == null ? null : lineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.material_no
     *
     * @return the value of operation.material_no
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.material_no
     *
     * @param materialNo the value for operation.material_no
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.old_material_no
     *
     * @return the value of operation.old_material_no
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public String getOldMaterialNo() {
        return oldMaterialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.old_material_no
     *
     * @param oldMaterialNo the value for operation.old_material_no
     *
     * @mbggenerated Mon Sep 25 11:40:02 CST 2017
     */
    public void setOldMaterialNo(String oldMaterialNo) {
        this.oldMaterialNo = oldMaterialNo == null ? null : oldMaterialNo.trim();
    }
}