package com.jimi.smt.esp_server.entity;

import java.util.Date;

public class ProgramBackup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.id
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.file_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.client
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String client;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.machine_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String machineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.version
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.machine_config
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String machineConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.program_no
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String programNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.line
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.effective_date
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.PCB_no
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String pcbNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.BOM
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String bom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.program_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String programName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.auditor
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_backup.create_time
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.id
     *
     * @return the value of program_backup.id
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.id
     *
     * @param id the value for program_backup.id
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.file_name
     *
     * @return the value of program_backup.file_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.file_name
     *
     * @param fileName the value for program_backup.file_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.client
     *
     * @return the value of program_backup.client
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.client
     *
     * @param client the value for program_backup.client
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setClient(String client) {
        this.client = client == null ? null : client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.machine_name
     *
     * @return the value of program_backup.machine_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.machine_name
     *
     * @param machineName the value for program_backup.machine_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setMachineName(String machineName) {
        this.machineName = machineName == null ? null : machineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.version
     *
     * @return the value of program_backup.version
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.version
     *
     * @param version the value for program_backup.version
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.machine_config
     *
     * @return the value of program_backup.machine_config
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getMachineConfig() {
        return machineConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.machine_config
     *
     * @param machineConfig the value for program_backup.machine_config
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setMachineConfig(String machineConfig) {
        this.machineConfig = machineConfig == null ? null : machineConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.program_no
     *
     * @return the value of program_backup.program_no
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getProgramNo() {
        return programNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.program_no
     *
     * @param programNo the value for program_backup.program_no
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setProgramNo(String programNo) {
        this.programNo = programNo == null ? null : programNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.line
     *
     * @return the value of program_backup.line
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.line
     *
     * @param line the value for program_backup.line
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.effective_date
     *
     * @return the value of program_backup.effective_date
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.effective_date
     *
     * @param effectiveDate the value for program_backup.effective_date
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setEffectiveDate(String effectiveDate) {
        this.effectiveDate = effectiveDate == null ? null : effectiveDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.PCB_no
     *
     * @return the value of program_backup.PCB_no
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getPcbNo() {
        return pcbNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.PCB_no
     *
     * @param pcbNo the value for program_backup.PCB_no
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setPcbNo(String pcbNo) {
        this.pcbNo = pcbNo == null ? null : pcbNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.BOM
     *
     * @return the value of program_backup.BOM
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getBom() {
        return bom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.BOM
     *
     * @param bom the value for program_backup.BOM
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setBom(String bom) {
        this.bom = bom == null ? null : bom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.program_name
     *
     * @return the value of program_backup.program_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.program_name
     *
     * @param programName the value for program_backup.program_name
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setProgramName(String programName) {
        this.programName = programName == null ? null : programName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.auditor
     *
     * @return the value of program_backup.auditor
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.auditor
     *
     * @param auditor the value for program_backup.auditor
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_backup.create_time
     *
     * @return the value of program_backup.create_time
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_backup.create_time
     *
     * @param createTime the value for program_backup.create_time
     *
     * @mbggenerated Thu Oct 19 14:12:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}