package com.jimi.smt.esp_server.entity;

public class ProgramItemBackup extends ProgramItemBackupKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.material_no
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private String materialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.specitification
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private String specitification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.position
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.quantity
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.material_no
     *
     * @return the value of program_item_backup.material_no
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.material_no
     *
     * @param materialNo the value for program_item_backup.material_no
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.specitification
     *
     * @return the value of program_item_backup.specitification
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public String getSpecitification() {
        return specitification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.specitification
     *
     * @param specitification the value for program_item_backup.specitification
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setSpecitification(String specitification) {
        this.specitification = specitification == null ? null : specitification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.position
     *
     * @return the value of program_item_backup.position
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.position
     *
     * @param position the value for program_item_backup.position
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.quantity
     *
     * @return the value of program_item_backup.quantity
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.quantity
     *
     * @param quantity the value for program_item_backup.quantity
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}