package com.jimi.smt.esp_server.entity;

public class ProgramItemBackupKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.program_id
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private String programId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.lineseat
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private String lineseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_backup.alternative
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    private Boolean alternative;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.program_id
     *
     * @return the value of program_item_backup.program_id
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.program_id
     *
     * @param programId the value for program_item_backup.program_id
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setProgramId(String programId) {
        this.programId = programId == null ? null : programId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.lineseat
     *
     * @return the value of program_item_backup.lineseat
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public String getLineseat() {
        return lineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.lineseat
     *
     * @param lineseat the value for program_item_backup.lineseat
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setLineseat(String lineseat) {
        this.lineseat = lineseat == null ? null : lineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_backup.alternative
     *
     * @return the value of program_item_backup.alternative
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public Boolean getAlternative() {
        return alternative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_backup.alternative
     *
     * @param alternative the value for program_item_backup.alternative
     *
     * @mbggenerated Tue Sep 26 15:29:29 CST 2017
     */
    public void setAlternative(Boolean alternative) {
        this.alternative = alternative;
    }
}