package com.jimi.smt.eps.printer.entity;

import java.util.Date;

public class StockLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.id
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.timestamp
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.material_no
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String materialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.quantity
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.operator
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.operation_time
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.position
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.custom
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String custom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.target_work_order
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String targetWorkOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.target_line
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private String targetLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.target_board_type
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    private Integer targetBoardType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.id
     *
     * @return the value of stock_log.id
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.id
     *
     * @param id the value for stock_log.id
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.timestamp
     *
     * @return the value of stock_log.timestamp
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.timestamp
     *
     * @param timestamp the value for stock_log.timestamp
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.material_no
     *
     * @return the value of stock_log.material_no
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.material_no
     *
     * @param materialNo the value for stock_log.material_no
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.quantity
     *
     * @return the value of stock_log.quantity
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.quantity
     *
     * @param quantity the value for stock_log.quantity
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.operator
     *
     * @return the value of stock_log.operator
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.operator
     *
     * @param operator the value for stock_log.operator
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.operation_time
     *
     * @return the value of stock_log.operation_time
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.operation_time
     *
     * @param operationTime the value for stock_log.operation_time
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.position
     *
     * @return the value of stock_log.position
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.position
     *
     * @param position the value for stock_log.position
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.custom
     *
     * @return the value of stock_log.custom
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getCustom() {
        return custom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.custom
     *
     * @param custom the value for stock_log.custom
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setCustom(String custom) {
        this.custom = custom == null ? null : custom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.target_work_order
     *
     * @return the value of stock_log.target_work_order
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getTargetWorkOrder() {
        return targetWorkOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.target_work_order
     *
     * @param targetWorkOrder the value for stock_log.target_work_order
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setTargetWorkOrder(String targetWorkOrder) {
        this.targetWorkOrder = targetWorkOrder == null ? null : targetWorkOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.target_line
     *
     * @return the value of stock_log.target_line
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public String getTargetLine() {
        return targetLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.target_line
     *
     * @param targetLine the value for stock_log.target_line
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setTargetLine(String targetLine) {
        this.targetLine = targetLine == null ? null : targetLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.target_board_type
     *
     * @return the value of stock_log.target_board_type
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public Integer getTargetBoardType() {
        return targetBoardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.target_board_type
     *
     * @param targetBoardType the value for stock_log.target_board_type
     *
     * @mbggenerated Tue Feb 06 14:43:30 CST 2018
     */
    public void setTargetBoardType(Integer targetBoardType) {
        this.targetBoardType = targetBoardType;
    }
}