package com.jimi.smt.eps.alarmsocket.entity;

public class ProgramItemVisitKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.lineseat
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private String lineseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.material_no
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private String materialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.program_id
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private String programId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.lineseat
     *
     * @return the value of program_item_visit.lineseat
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public String getLineseat() {
        return lineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.lineseat
     *
     * @param lineseat the value for program_item_visit.lineseat
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setLineseat(String lineseat) {
        this.lineseat = lineseat == null ? null : lineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.material_no
     *
     * @return the value of program_item_visit.material_no
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.material_no
     *
     * @param materialNo the value for program_item_visit.material_no
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.program_id
     *
     * @return the value of program_item_visit.program_id
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.program_id
     *
     * @param programId the value for program_item_visit.program_id
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setProgramId(String programId) {
        this.programId = programId == null ? null : programId.trim();
    }
}