package com.jimi.smt.eps.alarmsocket.entity;

import java.util.Date;

public class ProgramItemVisit extends ProgramItemVisitKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.scan_lineseat
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private String scanLineseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.scan_material_no
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private String scanMaterialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.last_operation_type
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer lastOperationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.store_issue_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer storeIssueResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.store_issue_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date storeIssueTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.feed_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer feedResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.feed_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date feedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.change_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer changeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.change_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_all_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer checkAllResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.check_all_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date checkAllTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.first_check_all_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Integer firstCheckAllResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.first_check_all_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date firstCheckAllTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_item_visit.last_operation_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    private Date lastOperationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.scan_lineseat
     *
     * @return the value of program_item_visit.scan_lineseat
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public String getScanLineseat() {
        return scanLineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.scan_lineseat
     *
     * @param scanLineseat the value for program_item_visit.scan_lineseat
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setScanLineseat(String scanLineseat) {
        this.scanLineseat = scanLineseat == null ? null : scanLineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.scan_material_no
     *
     * @return the value of program_item_visit.scan_material_no
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public String getScanMaterialNo() {
        return scanMaterialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.scan_material_no
     *
     * @param scanMaterialNo the value for program_item_visit.scan_material_no
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setScanMaterialNo(String scanMaterialNo) {
        this.scanMaterialNo = scanMaterialNo == null ? null : scanMaterialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.last_operation_type
     *
     * @return the value of program_item_visit.last_operation_type
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getLastOperationType() {
        return lastOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.last_operation_type
     *
     * @param lastOperationType the value for program_item_visit.last_operation_type
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setLastOperationType(Integer lastOperationType) {
        this.lastOperationType = lastOperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.store_issue_result
     *
     * @return the value of program_item_visit.store_issue_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getStoreIssueResult() {
        return storeIssueResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.store_issue_result
     *
     * @param storeIssueResult the value for program_item_visit.store_issue_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setStoreIssueResult(Integer storeIssueResult) {
        this.storeIssueResult = storeIssueResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.store_issue_time
     *
     * @return the value of program_item_visit.store_issue_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getStoreIssueTime() {
        return storeIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.store_issue_time
     *
     * @param storeIssueTime the value for program_item_visit.store_issue_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setStoreIssueTime(Date storeIssueTime) {
        this.storeIssueTime = storeIssueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.feed_result
     *
     * @return the value of program_item_visit.feed_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getFeedResult() {
        return feedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.feed_result
     *
     * @param feedResult the value for program_item_visit.feed_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setFeedResult(Integer feedResult) {
        this.feedResult = feedResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.feed_time
     *
     * @return the value of program_item_visit.feed_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getFeedTime() {
        return feedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.feed_time
     *
     * @param feedTime the value for program_item_visit.feed_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setFeedTime(Date feedTime) {
        this.feedTime = feedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.change_result
     *
     * @return the value of program_item_visit.change_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getChangeResult() {
        return changeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.change_result
     *
     * @param changeResult the value for program_item_visit.change_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setChangeResult(Integer changeResult) {
        this.changeResult = changeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.change_time
     *
     * @return the value of program_item_visit.change_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.change_time
     *
     * @param changeTime the value for program_item_visit.change_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_result
     *
     * @return the value of program_item_visit.check_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_result
     *
     * @param checkResult the value for program_item_visit.check_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setCheckResult(Integer checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_time
     *
     * @return the value of program_item_visit.check_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_time
     *
     * @param checkTime the value for program_item_visit.check_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_all_result
     *
     * @return the value of program_item_visit.check_all_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getCheckAllResult() {
        return checkAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_all_result
     *
     * @param checkAllResult the value for program_item_visit.check_all_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setCheckAllResult(Integer checkAllResult) {
        this.checkAllResult = checkAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.check_all_time
     *
     * @return the value of program_item_visit.check_all_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getCheckAllTime() {
        return checkAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.check_all_time
     *
     * @param checkAllTime the value for program_item_visit.check_all_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setCheckAllTime(Date checkAllTime) {
        this.checkAllTime = checkAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.first_check_all_result
     *
     * @return the value of program_item_visit.first_check_all_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Integer getFirstCheckAllResult() {
        return firstCheckAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.first_check_all_result
     *
     * @param firstCheckAllResult the value for program_item_visit.first_check_all_result
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setFirstCheckAllResult(Integer firstCheckAllResult) {
        this.firstCheckAllResult = firstCheckAllResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.first_check_all_time
     *
     * @return the value of program_item_visit.first_check_all_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getFirstCheckAllTime() {
        return firstCheckAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.first_check_all_time
     *
     * @param firstCheckAllTime the value for program_item_visit.first_check_all_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setFirstCheckAllTime(Date firstCheckAllTime) {
        this.firstCheckAllTime = firstCheckAllTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_item_visit.last_operation_time
     *
     * @return the value of program_item_visit.last_operation_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public Date getLastOperationTime() {
        return lastOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_item_visit.last_operation_time
     *
     * @param lastOperationTime the value for program_item_visit.last_operation_time
     *
     * @mbggenerated Wed May 02 15:43:05 CST 2018
     */
    public void setLastOperationTime(Date lastOperationTime) {
        this.lastOperationTime = lastOperationTime;
    }
}